name: news_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
  #   - images/a_dot_ham.jpeg

