name: news_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
  #   - images/a_dot_ham.jpeg

